### ISSUE TITLE
[E2E] message did not make it to the consumer

### ISSUE THREAD

**Issue by mooc9988** [AutoMQ/kafka#114]
```
================================================================================
test_id:    kafkatest.tests.core.reassign_partitions_test.ReassignPartitionsTest.test_reassign_partitions.bounce_brokers=False.reassign_from_offset_zero=False.metadata_quorum=REMOTE_KRAFT
status:     FAIL
run time:   8 minutes 17.514 seconds


    AssertionError("2350 acked message did not make it to the Consumer. They are: 12152, 12153, 12154, 12155, 12156, 12157, 12158, 12159, 12160, 12161, 12162, 12163, 12164, 12165, 12166, 12167, 12168, 12169, 12170, 12171...plus 2330 more. Total Acked: 14666, Total Consumed: 12316. The first 1000 missing messages were validated to ensure they are in Kafka's data files. 1000 were missing. This suggests data loss. Here are some of the messages not found in the data files: [12288, 12289, 12290, 12291, 12292, 12293, 12294, 12295, 12296, 12297]\n")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ducktape/tests/runner_client.py", line 186, in _do_run
    data = self.run_test()
  File "/usr/local/lib/python3.9/dist-packages/ducktape/tests/runner_client.py", line 246, in run_test
    return self.test_context.function(self.test)
  File "/usr/local/lib/python3.9/dist-packages/ducktape/mark/_mark.py", line 433, in wrapper
    return functools.partial(f, *args, **kwargs)(*w_args, **w_kwargs)
  File "/opt/kafka-dev/tests/kafkatest/tests/core/reassign_partitions_test.py", line 165, in test_reassign_partitions
    self.run_produce_consume_validate(core_test_action=lambda: self.reassign_partitions(bounce_brokers))
  File "/opt/kafka-dev/tests/kafkatest/tests/produce_consume_validate.py", line 108, in run_produce_consume_validate
    self.validate()
  File "/opt/kafka-dev/tests/kafkatest/tests/produce_consume_validate.py", line 132, in validate
    assert succeeded, error_msg
AssertionError: 2350 acked message did not make it to the Consumer. They are: 12152, 12153, 12154, 12155, 12156, 12157, 12158, 12159, 12160, 12161, 12162, 12163, 12164, 12165, 12166, 12167, 12168, 12169, 12170, 12171...plus 2330 more. Total Acked: 14666, Total Consumed: 12316. The first 1000 missing messages were validated to ensure they are in Kafka's data files. 1000 were missing. This suggests data loss. Here are some of the messages not found in the data files: [12288, 12289, 12290, 12291, 12292, 12293, 12294, 12295, 12296, 12297]


--------------------------------------------------------------------------------
```

**Comment by mooc9988** [comment]
More logs are added. Partitions failed to be reopened, exception stack :
```
[2023-08-29 08:56:41,006] ERROR [ElasticLogManager] Failed to create elastic log for test_topic-0 (kafka.log.es.ElasticLogManager)
java.lang.IllegalStateException: fetch empty from stream DefaultElasticStreamSlice{startOffsetInStream=708, stream=[id=163, startOffset=0, nextOffset=744], nextOffset=12, sealed=true} at offset 132
	at kafka.log.es.ElasticTimeIndex.parseEntry(ElasticTimeIndex.scala:69)
	at kafka.log.es.ElasticTimeIndex.$anonfun$lastEntryFromIndexFile$1(ElasticTimeIndex.scala:47)
	at kafka.log.es.ElasticTimeIndex.lastEntryFromIndexFile(ElasticTimeIndex.scala:45)
	at kafka.log.es.ElasticTimeIndex.<init>(ElasticTimeIndex.scala:33)
	at kafka.log.es.ElasticLogSegment$.apply(ElasticLogSegment.scala:391)
	at kafka.log.es.ElasticLogLoader.$anonfun$loadSegments$1(ElasticLogLoader.scala:107)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at kafka.log.es.ElasticLogLoader.loadSegments(ElasticLogLoader.scala:106)
	at kafka.log.es.ElasticLogLoader.load(ElasticLogLoader.scala:71)
	at kafka.log.es.ElasticLog$.apply(ElasticLog.scala:429)
	at kafka.log.es.ElasticLogManager.$anonfun$getOrCreateLog$1(ElasticLogManager.scala:50)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at kafka.log.es.ElasticLogManager.getOrCreateLog(ElasticLogManager.scala:47)
	at kafka.log.es.ElasticLogManager$.getOrCreateLog(ElasticLogManager.scala:150)
	at kafka.log.UnifiedLog$.applyElasticUnifiedLog(UnifiedLog.scala:1893)
	at kafka.log.UnifiedLog$.apply(UnifiedLog.scala:1839)
	at kafka.log.LogManager.$anonfun$getOrCreateLog$1(LogManager.scala:981)
	at scala.Option.getOrElse(Option.scala:201)
	at kafka.log.LogManager.getOrCreateLog(LogManager.scala:931)
	at kafka.cluster.Partition.createLog(Partition.scala:415)
	at kafka.cluster.Partition.maybeCreate$1(Partition.scala:390)
	at kafka.cluster.Partition.createLogIfNotExists(Partition.scala:397)
	at kafka.cluster.Partition.$anonfun$makeLeader$1(Partition.scala:674)
	at kafka.cluster.Partition.makeLeader(Partition.scala:630)
	at kafka.server.ReplicaManager.$anonfun$applyLocalLeadersDelta$3(ReplicaManager.scala:2223)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.ReplicaManager.$anonfun$applyLocalLeadersDelta$2(ReplicaManager.scala:2220)
	at kafka.server.ReplicaManager.$anonfun$applyLocalLeadersDelta$2$adapted(ReplicaManager.scala:2219)
	at kafka.utils.Implicits$MapExtensionMethods$.$anonfun$forKeyValue$1(Implicits.scala:62)
	at scala.collection.convert.JavaCollectionWrappers$JMapWrapperLike.foreachEntry(JavaCollectionWrappers.scala:399)
	at scala.collection.convert.JavaCollectionWrappers$JMapWrapperLike.foreachEntry$(JavaCollectionWrappers.scala:395)
	at scala.collection.convert.JavaCollectionWrappers$AbstractJMapWrapper.foreachEntry(JavaCollectionWrappers.scala:313)
	at kafka.server.ReplicaManager.applyLocalLeadersDelta(ReplicaManager.scala:2219)
	at kafka.server.ReplicaManager.kafka$server$ReplicaManager$$doPartitionLeadingOrFollowing$1(ReplicaManager.scala:2181)
	at kafka.server.ReplicaManager$$anon$3.run(ReplicaManager.scala:2199)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
